version: '2'
services:
  drone-server:
    image: drone/drone:2.9.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - drone
    volumes:
      - /opt/drone-data:/data
    environment:
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      DRONE_USER_FILTER: ${DRONE_USER_FILTER}
      DRONE_DATABASE_SECRET: ${DRONE_DATABASE_SECRET}
      DRONE_USER_CREATE: ${DRONE_USER_CREATE}
    restart: always

  drone-runner-docker:
    image: drone/drone-runner-docker:1
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: ${DRONE_RPC_PROTO}
      DRONE_RPC_HOST: ${DRONE_RPC_HOST}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_UI_USERNAME: ${DRONE_UI_USERNAME}
      DRONE_UI_PASSWORD: ${DRONE_UI_PASSWORD}
    restart: always

networks:
  drone:
    driver: bridge


